=== l3miage-khaddarm/ProjetTUX/src/DATA/xsd/dico.xsd
<?xml version="1.0"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XmlSchema.xsd to edit this template
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:tux="http://myGame/tux"
           targetNamespace="http://myGame/tux"
           elementFormDefault="qualified">
    <!-- la racine dictionnaire de type Dictionnaire -->
    <xs:element name="dictionnaire" type="tux:Dictionnaire"/>
    <!-- l'élément dictionnaire qui contient mot de type Mots-->
    <xs:complexType  name="Dictionnaire">
        <xs:sequence>
            <xs:element name="mot" type="tux:Mots" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
    <!--l'élément mot qui contient contenu (string) et niveau(int) -->
    </xs:complexType>
    <xs:complexType  name="Mots">
        <xs:sequence>
            <xs:element name="contenu" />
            <xs:element name="niveau" type="tux:Niveau"/>
        </xs:sequence>
    </xs:complexType>
    <!--Niveau de type int -->
    <xs:simpleType name="Niveau">
        <xs:restriction base="xs:int" >
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="5"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== l3miage-khaddarm/ProjetTUX/src/DATA/xml/dico.xml
<?xml version="1.0" encoding="UTF-8"?>
<tux:dictionnaire
            xmlns:xs='http://www.w3.org/2001/XMLSchema-instance'
            xmlns:tux="http://myGame/tux"
            xs:schemaLocation='http://myGame/tux ../xsd/dico.xsd'>
    <!-- on a opté pour un élément tux:mot qui contient deux éléments : tux:contenu c'est à dire le mot en question et tux:niveau-->
    <tux:mot> 
        <tux:contenu>maitenant</tux:contenu>
        <tux:niveau>2</tux:niveau>
    </tux:mot>
    <tux:mot> 
        <tux:contenu>prompt</tux:contenu>
        <tux:niveau>5</tux:niveau>
    </tux:mot>
    <tux:mot> 
        <tux:contenu>instance</tux:contenu>
        <tux:niveau>4</tux:niveau>
    </tux:mot>
    <tux:mot> 
        <tux:contenu>demain</tux:contenu>
        <tux:niveau>1</tux:niveau>
    </tux:mot>
    <tux:mot> 
        <tux:contenu>horizon</tux:contenu>
        <tux:niveau>3</tux:niveau>
    </tux:mot>
    <tux:mot> 
        <tux:contenu>ludique</tux:contenu>
        <tux:niveau>3</tux:niveau>
    </tux:mot>
    <tux:mot> 
        <tux:contenu>planète</tux:contenu>
        <tux:niveau>2</tux:niveau>
    </tux:mot>
    <tux:mot> 
        <tux:contenu>salut</tux:contenu>
        <tux:niveau>1</tux:niveau>
    </tux:mot>
    <tux:mot> 
        <tux:contenu>écart-type</tux:contenu>
        <tux:niveau>3</tux:niveau>
    </tux:mot>

</tux:dictionnaire>
